[build]
  publish = "build"

# Use max-age > 0 or else this won't work!
# Source: <https://community.netlify.com/t/netlify-ignores-cache-control-for-304/2912/14>

[[headers]]
  for = "/assets/javascripts/*.js"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/assets/stylesheets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/assets/fonts/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/assets/fonts/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/assets/fonts/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/assets/fonts/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=300"
