name: Deploy site to Netlify
on:
  workflow_call:
    inputs:
      netlify-environment:
        description: 'The Netlify environment you want to deploy to ("preview" or "production").'
        required: true
        type: string
      subrepo-name:
        description: 'The name of the repository where this workflow was called from.'
        required: false
        type: string
      subrepo-pull-request-number:
        description: 'The number of the issue or pull request where this workflow was called from.'
        required: false
        type: number
    secrets:
      NETLIFY_SITE_ID:
        description: 'The Netlify site ID to deploy to.'
        required: true
      NETLIFY_AUTH_TOKEN:
        description: 'The Netlify auth token to use.'
        required: true
      CLONE_SUBREPO_TOKEN:
        description: 'The GitHub token to use to clone the subrepo.'
        required: false
      UPDATE_DEPLOYMENT_STATUS_TOKEN:
        description: 'The GitHub token to use to update content repos with deployment statuses.'
        required: false
  workflow_dispatch:
    inputs:
      netlify-environment:
        description: 'The Netlify environment you want to deploy to ("preview" or "production").'
        required: true
        type: string
      subrepo-name:
        description: 'The name of the subrepository that has new changes you want to deploy.'
        required: false
        type: string
      subrepo-ref:
        description: 'The ref of the subrepo you want to check out.'
        required: false
        type: string
      subrepo-pull-request-number:
        description: 'The number of the issue or pull request where this workflow was called from.'
        required: false
        type: number
      clone-subrepo-token:
        description: 'The GitHub token to use to clone the subrepo.'
        required: false
        type: string
      update-deployment-status-token:
        description: 'The GitHub token to use to update content repos with deployment statuses.'
        required: false
        type: string
env:
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  UPDATE_DEPLOYMENT_STATUS_TOKEN: ${{ inputs.update-deployment-status-token || secrets.UPDATE_DEPLOYMENT_STATUS_TOKEN }}
  CLONE_SUBREPO_TOKEN: ${{ inputs.clone-subrepo-token || secrets.CLONE_SUBREPO_TOKEN }}
  NETLIFY_ENVIRONMENT: ${{ inputs.netlify-environment }}
  SUBREPO_NAME: ${{ inputs.subrepo-name }}
  SUBREPO_PULL_REQUEST_NUMBER: ${{ inputs.subrepo-pull-request-number }}
  SUBREPO_REF: ${{ inputs.subrepo-ref }}
jobs:
  deploy-to-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Post initial comment to referring pull request
        id: post-comment
        if: ${{ env.SUBREPO_NAME && env.SUBREPO_PULL_REQUEST_NUMBER && env.SUBREPO_PULL_REQUEST_NUMBER != '0' }}
        # If e.g. Dependabot creates the PR then the generated GitHub token
        # won't have write access to the pull request so this step will fail
        continue-on-error: true
        uses: actions/github-script@v8
        with:
          github-token: ${{ env.SUBREPO_NAME == 'elliotwinkler.com' && github.token || env.UPDATE_DEPLOYMENT_STATUS_TOKEN }}
          script: |
            const result = await github.rest.issues.createComment({
              issue_number: process.env.SUBREPO_PULL_REQUEST_NUMBER,
              owner: 'mcmire',
              repo: process.env.SUBREPO_NAME,
              body: 'Deploying your branch, please wait...\n\n(This comment will automatically update when complete.)'
            })
            console.log(result);
            return result;
      - uses: actions/checkout@v6
        with:
          path: elliotwinkler.com
      # TODO: Iterate through all subrepos and perform these steps
      # in order to set up the repo
      # Then all we have to really do here is just check out the right ref
      # and re-run `git lfs` again
      - if: ${{ env.SUBREPO_NAME && env.SUBREPO_REF && env.CLONE_SUBREPO_TOKEN }}
        uses: actions/checkout@v6
        with:
          repository: mcmire/${{ env.SUBREPO_NAME }}
          ref: ${{ env.SUBREPO_REF }}
          token: ${{ env.CLONE_SUBREPO_TOKEN }}
          path: ${{ env.SUBREPO_NAME }}
          lfs: true
      - if: ${{ !env.SUBREPO_REF && env.CLONE_SUBREPO_TOKEN }}
        uses: actions/checkout@v6
        with:
          repository: mcmire/personal-content--writings
          ref: main
          token: ${{ env.CLONE_SUBREPO_TOKEN }}
          path: personal-content--writings
          lfs: true
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install Yarn via Corepack
        run: corepack enable
        working-directory: elliotwinkler.com
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: elliotwinkler.com/yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: elliotwinkler.com
      - name: Build project
        run: yarn build
        working-directory: elliotwinkler.com
      - name: Deploy to Netlify (in ${{ env.NETLIFY_ENVIRONMENT }} mode)
        id: deploy
        run: |
          if [[ "$NETLIFY_ENVIRONMENT" == "production" ]]; then
            yarn netlify deploy --dir dist --prod --json > deploy.json
          else
            yarn netlify deploy --dir dist --json > deploy.json
          fi
          echo DEPLOYMENT_URL="$(jq -r '.deploy_url // .url' < deploy.json)" >> "$GITHUB_OUTPUT"
        shell: bash
        working-directory: elliotwinkler.com
      - name: Update comment on referring pull request
        if: ${{ env.SUBREPO_NAME && steps.post-comment.outputs.result && steps.deploy.outputs.DEPLOYMENT_URL }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.SUBREPO_NAME == 'elliotwinkler.com' && github.token || env.UPDATE_DEPLOYMENT_STATUS_TOKEN }}
          script: |
            const previousCommentResponse = JSON.parse(process.env.PREVIOUS_COMMENT_RESPONSE);
            await github.rest.issues.updateComment({
              owner: 'mcmire',
              repo: process.env.SUBREPO_NAME,
              comment_id: previousCommentResponse.data.id,
              body: `:rocket: This branch has been successfully deployed at: <${process.env.DEPLOYMENT_URL}>`
            })
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.DEPLOYMENT_URL }}
          PREVIOUS_COMMENT_RESPONSE: ${{ steps.post-comment.outputs.result }}
      - name: Update comment on failure
        if: ${{ failure() && steps.post-comment.outputs.result }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.SUBREPO_NAME == 'elliotwinkler.com' && github.token || env.UPDATE_DEPLOYMENT_STATUS_TOKEN }}
          script: |
            const previousCommentResponse = JSON.parse(process.env.PREVIOUS_COMMENT_RESPONSE);
            const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            await github.rest.issues.updateComment({
              owner: 'mcmire',
              repo: process.env.SUBREPO_NAME,
              comment_id: previousCommentResponse.data.id,
              body: `:x: Deployment failed. Check the [actions log](${runUrl}) for details.`
            })
        env:
          PREVIOUS_COMMENT_RESPONSE: ${{ steps.post-comment.outputs.result }}
