name: Main workflow
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: write
jobs:
  extract-repository-name:
    name: Extract repository name
    runs-on: ubuntu-latest
    steps:
      - id: repository-name
        run: |
          github_repository_name="${GITHUB_REPOSITORY#"$GITHUB_REPOSITORY_OWNER/"}"
          echo "GITHUB_REPOSITORY_NAME=$github_repository_name" >> "$GITHUB_OUTPUT"
    outputs:
      GITHUB_REPOSITORY_NAME: ${{ steps.repository-name.outputs.GITHUB_REPOSITORY_NAME }}
  deploy-to-netlify:
    name: Deploy to Netlify
    needs: extract-repository-name
    uses: ./.github/workflows/deploy-to-netlify.yml
    with:
      netlify-environment: preview
      subrepo-name: ${{ needs.extract-repository-name.outputs.GITHUB_REPOSITORY_NAME }}
      subrepo-pull-request-number: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || 0 }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      CLONE_SUBREPO_TOKEN: ${{ secrets.CLONE_SUBREPO_TOKEN }}
